# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        echo "skopeo copy docker://docker.io/odoo:10.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:10.0"
        skopeo copy docker://docker.io/odoo:10.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:10.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/odoo:11.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:11.0"
        skopeo copy docker://docker.io/odoo:11.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:11.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/odoo:12.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:12.0"
        skopeo copy docker://docker.io/odoo:12.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:12.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/odoo:13.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:13.0"
        skopeo copy docker://docker.io/odoo:13.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:13.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/odoo:14.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:14.0"
        skopeo copy docker://docker.io/odoo:14.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:14.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/odoo:15.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:15.0"
        skopeo copy docker://docker.io/odoo:15.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:15.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/odoo:16.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:16.0"
        skopeo copy docker://docker.io/odoo:16.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:16.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/odoo:17.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:17.0"
        skopeo copy docker://docker.io/odoo:17.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:17.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/odoo:8.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:8.0"
        skopeo copy docker://docker.io/odoo:8.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:8.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/odoo:9.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:9.0"
        skopeo copy docker://docker.io/odoo:9.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/odoo:9.0 || echo "skopeo copy failed, current task skip"
