# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        echo "skopeo copy docker://docker.io/portainer/portainer:1.10.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.10.0"
        skopeo copy docker://docker.io/portainer/portainer:1.10.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.10.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.10.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.10.1"
        skopeo copy docker://docker.io/portainer/portainer:1.10.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.10.1 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.10.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.10.2"
        skopeo copy docker://docker.io/portainer/portainer:1.10.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.10.2 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.11.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.11.0"
        skopeo copy docker://docker.io/portainer/portainer:1.11.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.11.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.11.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.11.1"
        skopeo copy docker://docker.io/portainer/portainer:1.11.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.11.1 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.16.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.16.0"
        skopeo copy docker://docker.io/portainer/portainer:1.16.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.16.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.17.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.17.0"
        skopeo copy docker://docker.io/portainer/portainer:1.17.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.17.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.20.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.20.0"
        skopeo copy docker://docker.io/portainer/portainer:1.20.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.20.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.20.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.20.1"
        skopeo copy docker://docker.io/portainer/portainer:1.20.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.20.1 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.21.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.21.0"
        skopeo copy docker://docker.io/portainer/portainer:1.21.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.21.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.22.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.22.0"
        skopeo copy docker://docker.io/portainer/portainer:1.22.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.22.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.22.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.22.1"
        skopeo copy docker://docker.io/portainer/portainer:1.22.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.22.1 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.22.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.22.2"
        skopeo copy docker://docker.io/portainer/portainer:1.22.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.22.2 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.23.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.23.0"
        skopeo copy docker://docker.io/portainer/portainer:1.23.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.23.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.23.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.23.1"
        skopeo copy docker://docker.io/portainer/portainer:1.23.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.23.1 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.23.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.23.2"
        skopeo copy docker://docker.io/portainer/portainer:1.23.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.23.2 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.24.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.24.0"
        skopeo copy docker://docker.io/portainer/portainer:1.24.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.24.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.24.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.24.1"
        skopeo copy docker://docker.io/portainer/portainer:1.24.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.24.1 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.24.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.24.2"
        skopeo copy docker://docker.io/portainer/portainer:1.24.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.24.2 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.25.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.25.0"
        skopeo copy docker://docker.io/portainer/portainer:1.25.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.25.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.9.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.9.0"
        skopeo copy docker://docker.io/portainer/portainer:1.9.0 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.9.0 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.9.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.9.1"
        skopeo copy docker://docker.io/portainer/portainer:1.9.1 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.9.1 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.9.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.9.2"
        skopeo copy docker://docker.io/portainer/portainer:1.9.2 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.9.2 || echo "skopeo copy failed, current task skip"
        echo "skopeo copy docker://docker.io/portainer/portainer:1.9.3 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.9.3"
        skopeo copy docker://docker.io/portainer/portainer:1.9.3 docker://registry.cn-hangzhou.aliyuncs.com/lyf110-docker-repo/portainer_portainer:1.9.3 || echo "skopeo copy failed, current task skip"
